export const projectData = [
  {
    title: "Ecommerce Mobile app",
    img: "/images/Mediquik.png",
    desc: "Created an E-commerce android application based on the concept of 1MG.Developed 2 more application for one for admin and other for delivery partner. ",
    code: "/",
    demo: "https://www.youtube.com/watch?v=xVs6zw1NtBc&ab_channel=AlroyFernandes",
  },
  {
    title: "Pednekar Jewellery Website",
    img: "/images/Pednekar.png",
    desc: "Created a E-COMMERCE application based on the concept of TANISHQ having features similar to modern applications like flipkart,amazon. ",
    code: "/",
    demo: "https://www.pednekarjewellery.com/",
  },
  {
    title: "Static Car Rental WebPage",
    img: "/images/MogaWheels.png",
    desc: "Created a website to display various services,vehicles provided by the client who is based in Calangute,Goa",
    code: "/",
    demo: "https://car-rental-two.vercel.app/",
  },
  {
    title: "Photography Website",
    img: "/images/3gFotos.png",
    desc: "Created a static website for a client based in Goa to help scale his business",
    code: "/",
    demo: "https://photography-client.vercel.app/",
  },
  {
    title: " Static Hotel Website",
    img: "/images/VillaGG.png",
    desc: "Created a Single Page webpage(no booking facility) for a client to showcase various services they offer.",
    code: "/",
    demo: "https://villa-gods-gift.000webhostapp.com/",
  },
  {
    title: "Static Villa Website",
    img: "/images/VillaAA.png",
    desc: "Created a Landing Page  for a client to showcase various services he is providing in the Real-Estate.",
    code: "/",
    demo: "https://real-estate-app-mu-two.vercel.app/",
  },
  {
    title: "Social media application",
    img: "/images/facebook-mern.PNG",
    desc: "This application is build using the MERN stack with basically all features  which are present in any social media application with real-time chat with messenger.",
    code: "https://github.com/Alroyfernz/Facebook-mern",
    demo: "https://facebook-merng.herokuapp.com/",
  },

  {
    title: "Video chat application",
    img: "/images/anymeet.png",
    desc: "Developed a Real-Time Chat application which allows users to have video calls.This application is build using ReactJs ,Nodejs and socket.io",
    code: "https://github.com/Alroyfernz/VideoApp-reactjs",
    demo: "https://video-app-reactjs.vercel.app/",
  },

  {
    title: "Youtube-clone",
    img: "/images/youtube.PNG",
    desc: "This Youtube-clone is build using React/Redux,Firbase for Oauth and youtube data api to fetch all videos.",
    code: "https://github.com/Alroyfernz/Youtube-CLone",
    demo: "https://clone-33642.web.app",
  },
  {
    title: "Crypto-tracker",
    img: "https://miro.medium.com/max/2000/1*dszBS7o1VXa1eDfkrnaP4A.png",
    desc: "This app is build using React/context api which fetches prices of various crytocurrencies.",
    code: "",
    demo: "https://crytocurrency-app.vercel.app/",
  },
  {
    title: "Google-clone",
    img: "/images/google.PNG",
    desc: "This Google-clone is build using React/redux having features like search,which uses google serach api to fetch results.",
    code: "https://github.com/Alroyfernz/Google-clone",
    demo: "https://google-clone-bn313qtoe-alroyfernz.vercel.app/",
  },
];
